### ISSUE TITLE
deploy local via docker

### ISSUE THREAD

**Issue by guinanlin** [bigcapitalhq/bigcapital#539]
ref doc: https://docs.bigcapital.app/deployment/docker

envoy yml

```
[root@ERP-Basic-guanfangbanbenyanshi envoy]# cat envoy.yaml 
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0 
          port_value: 1080 
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains: ['*']
                      routes:
                        - match:
                            prefix: '/api'
                          route:
                            cluster: dynamic_server
                        - match:
                            prefix: '/'
                          route:
                            cluster: webapp
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: dynamic_server
      connect_timeout: 0.25s
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: dynamic_server
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: server
                      port_value: 3000

    - name: webapp
      connect_timeout: 0.25s
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: webapp
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: webapp 
                      port_value: 80
```

docker process:

![](https://pic.imgdb.cn/item/669bfcbcd9c307b7e9e5644c.png)

The host: 192.168.8.92

Now I can surf the 192.168.8.92:1980

But Cannot surf the 192.168.8.92:1080, and it turn back reject connection.

**Comment by guinanlin** [comment]
after correct docker-compose.prod.yml, it works , tks.

```
[root@ERP-Basic-guanfangbanbenyanshi bigcapital]# cat docker-compose.prod.yml 
# This is a production version of the Bigcapital docker-compose.yml file.

version: '3.3'

services:
  proxy:
    image: envoyproxy/envoy:v1.31-latest
    depends_on:
      - server
      - webapp
    ports:
      - '${PUBLIC_PROXY_PORT:-1080}:1080'
      - '${PUBLIC_PROXY_SSL_PORT:-443}:443'
```
